### ISSUE TITLE
Fix manage.py createjob

### ISSUE THREAD

**Issue by mgax** [mgax/vmck#30]
Running `pipenv run ./manage.py createjob` (as described in the Readme) throws an `AttributeError: module 'vmck.nomad' has no attribute 'create_job'`.

**Comment by dixi3** [comment]
Hi from what i can tell createjob should call jobs.create(backend), the same thing evaluate does, what is the difference between createjob and evaluate?

**Comment by mgax** [comment]
> what is the difference between createjob and evaluate

They do the same thing, we should keep only one. Let's say `createjob` because it's closer to the API naming.
