### ISSUE TITLE
Expose models in django admin

### ISSUE THREAD

**Issue by mgax** [mgax/vmck#37]
Let's add [our models](https://github.com/mgax/vmck/blob/f525cef5f537b0e3c1e473632016c8cab42621b0/vmck/models.py) to the django [admin site](https://docs.djangoproject.com/en/2.2/#the-admin)

**Comment by dixi3** [comment]
Do the models need custom actions?

**Comment by mgax** [comment]
> Do the models need custom actions?

No, just the default behaviour.
